/*
in allegato un esercizio con solo gli oggetti della GUI ...
si tratta di aggiungere numeri ad un array (arraylist visualizzato in jlist) e poi farne delle statistiche ( l'ordinamento e soprattutto il calcolo della Moda sono abbastanza complesse non impazzite!!!)
date dei nomi sensati agli oggetti prima di iniziare a scrivere codice,dovete anche  creare l'arraylist, vi ho messo solo gli oggetti grafici...
buon divertimento
Per la Moda dovrete usare degli array di appoggio immaginate di risolverlo sulla carta
es. numeri inseriti:
2 - 2 - 4 - 1 - 5- 3- 2- 1- 3
la moda e' 2 ovvero il numero che e' comparso piu' volte nella sequenza
 */
package tss.ciac.eserciziostatistica;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Paolo
 */
public class App extends javax.swing.JFrame {

    // dichiarazione variabili globali
    static ArrayList<Integer> numeri = new ArrayList<Integer>();

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListNumeri = new javax.swing.JList<>();
        jTextFieldNumeroDaInserire = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonInserisci = new javax.swing.JButton();
        jButtonModa = new javax.swing.JButton();
        jButtonMedia = new javax.swing.JButton();
        jButtonSomma = new javax.swing.JButton();
        jButtonMinimo = new javax.swing.JButton();
        jButtonMassimo = new javax.swing.JButton();
        jLabelMassimo = new javax.swing.JLabel();
        jLabelMinimo = new javax.swing.JLabel();
        jLabelSomma = new javax.swing.JLabel();
        jLabelMedia = new javax.swing.JLabel();
        jLabelModa = new javax.swing.JLabel();
        jButtonOrdina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListNumeri);

        jLabel1.setText("Numero da inserire");

        jButtonInserisci.setText("Inserisci");
        jButtonInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserisciActionPerformed(evt);
            }
        });

        jButtonModa.setText("Moda");
        jButtonModa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModaActionPerformed(evt);
            }
        });

        jButtonMedia.setText("Media");
        jButtonMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMediaActionPerformed(evt);
            }
        });

        jButtonSomma.setText("Somma");
        jButtonSomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSommaActionPerformed(evt);
            }
        });

        jButtonMinimo.setText("Minimo");
        jButtonMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimoActionPerformed(evt);
            }
        });

        jButtonMassimo.setText("Massimo");
        jButtonMassimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMassimoActionPerformed(evt);
            }
        });

        jLabelMassimo.setText("       ");

        jLabelMinimo.setText("       ");

        jLabelSomma.setText("       ");

        jLabelMedia.setText("       ");

        jLabelModa.setText("       ");

        jButtonOrdina.setText("Ordina");
        jButtonOrdina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNumeroDaInserire)
                            .addComponent(jButtonInserisci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonOrdina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMassimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMinimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSomma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMedia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMassimo)
                            .addComponent(jLabelMinimo)
                            .addComponent(jLabelSomma)
                            .addComponent(jLabelMedia)
                            .addComponent(jLabelModa))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumeroDaInserire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInserisci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jButtonOrdina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMassimo)
                            .addComponent(jLabelMassimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMinimo)
                            .addComponent(jLabelMinimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSomma)
                            .addComponent(jLabelSomma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMedia)
                            .addComponent(jLabelMedia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModa)
                            .addComponent(jLabelModa)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserisciActionPerformed
        // TODO add your handling code here:
        String n = jTextFieldNumeroDaInserire.getText();
        if (!n.isEmpty()) {
            numeri.add(Integer.parseInt(n));
            refreshList();
        }
    }//GEN-LAST:event_jButtonInserisciActionPerformed

    private void jButtonMassimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMassimoActionPerformed
        // TODO add your handling code here:
        int max = 0;
        for (int i = 0; i < numeri.size(); i++) {
            if (numeri.get(i) > max) {
                max = numeri.get(i);
            }
        }
        jLabelMassimo.setText("" + max);

    }//GEN-LAST:event_jButtonMassimoActionPerformed

    private void jButtonMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMediaActionPerformed
        // TODO add your handling code here:
        float media;
        int somma = 0;
        for (int i = 0; i < numeri.size(); i++) {
            somma += numeri.get(i);
        }
        media = somma / numeri.size();
        jLabelMedia.setText("" + media);
    }//GEN-LAST:event_jButtonMediaActionPerformed

    private void jButtonMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimoActionPerformed
        // TODO add your handling code here:
        int min = 0;
        for (int i = 0; i < numeri.size(); i++) {
            if (numeri.get(i) < min) {
                min = numeri.get(i);
            }
        }
        jLabelMinimo.setText("" + min);
    }//GEN-LAST:event_jButtonMinimoActionPerformed

    private void jButtonSommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSommaActionPerformed
        // TODO add your handling code here:
        int somma = 0;
        for (int i = 0; i < numeri.size(); i++) {
            somma += numeri.get(i);
        }
        jLabelSomma.setText("" + somma);
    }//GEN-LAST:event_jButtonSommaActionPerformed

    private void jButtonModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModaActionPerformed
        // TODO add your handling code here:
        int moda=0;
        int occorrenze = 0, occorrenzeModa = 0;
        ArrayList<Integer> numeriMod = (ArrayList<Integer>) numeri.clone(); // copia dell'ArrayList numeri senza i valori già controllati

        while (0 < numeriMod.size()) {
            occorrenze = 0;
            for (int j = 0; j < numeriMod.size(); j++) {
                if (numeriMod.get(j) == numeriMod.get(0)) {
                    occorrenze++;
                    if (occorrenze > occorrenzeModa) {
                        occorrenzeModa = occorrenze;
                        moda = numeriMod.get(j); 
                    }
                    numeriMod.remove(j); // tolgo il valore appena controllato
                }
            }

        }
        jLabelModa.setText(""+moda);
    }//GEN-LAST:event_jButtonModaActionPerformed

    private void jButtonOrdinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdinaActionPerformed
        // TODO add your handling code here:
        //scorro un numero per volta
            for (int i = 1; i < numeri.size(); i++) {
                boolean scambio = false;
                for (int j = 1; j < numeri.size(); j++) {
                    if (numeri.get(j - 1) > numeri.get(j)) {
                        //scambio
                        int tmp = numeri.get(j - 1);
                        numeri.set(j - 1, numeri.get(j));
                        numeri.set(j, tmp);
                        scambio = true;
                    }
                    //se nessuno scambio esco

                }
                if (scambio == false) {
                    break;
                }
            }
            refreshList();
    }//GEN-LAST:event_jButtonOrdinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    private void refreshList() {
        DefaultListModel listModel = new DefaultListModel();
        for (Integer i : numeri) {
            //aggiungi String alla lista
            listModel.addElement(i);
        }
        jListNumeri.setModel(listModel); // scrive nell'oggetto grafico jListUsers
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserisci;
    private javax.swing.JButton jButtonMassimo;
    private javax.swing.JButton jButtonMedia;
    private javax.swing.JButton jButtonMinimo;
    private javax.swing.JButton jButtonModa;
    private javax.swing.JButton jButtonOrdina;
    private javax.swing.JButton jButtonSomma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMassimo;
    private javax.swing.JLabel jLabelMedia;
    private javax.swing.JLabel jLabelMinimo;
    private javax.swing.JLabel jLabelModa;
    private javax.swing.JLabel jLabelSomma;
    private javax.swing.JList<String> jListNumeri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNumeroDaInserire;
    // End of variables declaration//GEN-END:variables
}
