
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Statistic extends javax.swing.JFrame {

    /**
     * Creates new form Statistic
     */
    ArrayList<Integer> lista = new ArrayList<Integer>();

    public Statistic() {
        initComponents();
        txNumber.requestFocus(true);
        txNumber.setSelectionStart(0);
        txNumber.setSelectionEnd(999);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        btnAddnumber = new javax.swing.JButton();
        jButtonsomma = new javax.swing.JButton();
        jButtonmedia = new javax.swing.JButton();
        jButtonminimo = new javax.swing.JButton();
        jButtonmassimo = new javax.swing.JButton();
        jButtonmoda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneris = new javax.swing.JTextPane();
        jButtonsort = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txNumber.setText("0");
        txNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNumberActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList);

        btnAddnumber.setText("Add number");
        btnAddnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddnumberActionPerformed(evt);
            }
        });

        jButtonsomma.setText("Somma");
        jButtonsomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsommaActionPerformed(evt);
            }
        });

        jButtonmedia.setText("Media");
        jButtonmedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmediaActionPerformed(evt);
            }
        });

        jButtonminimo.setText("Minimo");
        jButtonminimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonminimoActionPerformed(evt);
            }
        });

        jButtonmassimo.setText("Massimo");
        jButtonmassimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmassimoActionPerformed(evt);
            }
        });

        jButtonmoda.setText("Moda");
        jButtonmoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPaneris);

        jButtonsort.setText("Ordina elenco");
        jButtonsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsortActionPerformed(evt);
            }
        });

        jLabel1.setText("Risultati Operazioni");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Statistiche elenco numbers");

        jLabel3.setText("Elenco numbers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(189, 189, 189))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButtonmoda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonsomma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonmassimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonminimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonmedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonsort, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                                    .addComponent(jScrollPane2))
                                .addContainerGap())))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddnumber)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonsomma)
                            .addComponent(jButtonmedia)
                            .addComponent(txNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonminimo)
                                    .addComponent(jButtonmassimo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonmoda)
                                    .addComponent(jButtonsort))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumberActionPerformed

    private void jButtonminimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonminimoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String tx = "Il minimo e' : ";
        jTextPaneris.setText(tx + minimo());
    }//GEN-LAST:event_jButtonminimoActionPerformed

    private void jButtonmassimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmassimoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String tx = "il massimo e' : ";
        jTextPaneris.setText(tx + massimo());
    }//GEN-LAST:event_jButtonmassimoActionPerformed

    private void jButtonmodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String tx = "La Moda e' : ";
        jTextPaneris.setText(tx + moda());
    }//GEN-LAST:event_jButtonmodaActionPerformed

    private void jButtonsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsortActionPerformed
        // TODO add your handling code here:
        sort();
    }//GEN-LAST:event_jButtonsortActionPerformed

    private void btnAddnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddnumberActionPerformed
        // TODO add your handling code here:
        try {
            int n = Integer.parseInt(txNumber.getText());
            lista.add(n);
            refreshList();
            txNumber.setFocusable(true);
            txNumber.requestFocus(true);

            txNumber.setSelectionStart(0);
            txNumber.setSelectionEnd(999);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "non e' un numero!!!");
        }

    }//GEN-LAST:event_btnAddnumberActionPerformed

    private void jButtonsommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsommaActionPerformed
        // TODO add your handling code here:
        String tx = "La somma e' : ";
        jTextPaneris.setText(tx + somma());
    }//GEN-LAST:event_jButtonsommaActionPerformed

    private void jButtonmediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmediaActionPerformed
        // TODO add your handling code here:
        String tx = "La media e' : ";
        jTextPaneris.setText(tx + media());
    }//GEN-LAST:event_jButtonmediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddnumber;
    private javax.swing.JButton jButtonmassimo;
    private javax.swing.JButton jButtonmedia;
    private javax.swing.JButton jButtonminimo;
    private javax.swing.JButton jButtonmoda;
    private javax.swing.JButton jButtonsomma;
    private javax.swing.JButton jButtonsort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPaneris;
    private javax.swing.JTextField txNumber;
    // End of variables declaration//GEN-END:variables

    private void refreshList() {
        DefaultListModel listModel = new DefaultListModel();
        //gli aggiungi i valori
        for (Integer n : lista) {
            //aggiungi frase alla lista
            listModel.addElement(n);
        }
        jList.setModel(listModel);

    }

    private int somma() {
        int ris = 0;
        for (Integer n : lista) {
            //aggiungi frase alla lista
            ris += n;
        }
        return ris;

    }

    private float media() {
        float ris = 0;
        for (Integer n : lista) {
            //aggiungi frase alla lista
            ris += n;
        }
        ris = ris / lista.size();
        return ris;

    }

    private float minimo() {
        float ris = 0;
        if (lista.size() > 0) {
            ris = lista.get(0);
            for (Integer n : lista) {
                if (ris > n) {
                    ris = n;
                }
            }
        }
        return ris;

    }

    private float massimo() {
        float ris = 0;
        if (lista.size() > 0) {
            ris = lista.get(0);
            for (Integer n : lista) {
                if (ris < n) {
                    ris = n;
                }
            }
        }
        return ris;

    }
    private float moda() {
        int cmax = 0;
        int nmax = 0;

        if (lista.size() > 0) {
            //scorro un numero per voltae guardo quante volte compare

            for (Integer n : lista) {
                int c = 0;
                for (Integer m : lista) {
                    if (n == m) {
                        c++;
                    }
                }
                if (c > cmax) {
                    nmax = n;
                    cmax = c;
                }
            }
        }
        return nmax;
    }

    private void sort() {
        System.out.println("Statistic.sort()" + lista.get(0) + " - " + lista.get(1) + "- " + lista.size());

        if (lista.size() > 0) {
            //scorro un numero per voltae guardo quante volte compare
            for (int i = 1; i < lista.size(); i++) {
                boolean scambio = false;
                for (int j = 1; j < lista.size(); j++) {
                    if (lista.get(j - 1) > lista.get(j)) {
                        //scambio
                        int tmp = lista.get(j - 1);
                        lista.set(j - 1, lista.get(j));
                        lista.set(j, tmp);
                        scambio = true;
                        System.out.println("sort()" + lista.get(j - 1) + " - " + lista.get(j));
                    }
                    //se nessuno scambio basta esco

                }
                if (scambio == false) {
                    break;
                }
            }
            refreshList();
        }
    }

}
