/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;

/**
 *
 * @author luca lorenzo guerrin
 */
public class Mondobici extends javax.swing.JFrame {

    Bici bike;

    /**
     * Creates new form Mondobici
     */
    public Mondobici() {
        bike = new Bici(0, 0, 0, 90);

        initComponents();
        btnBici.setText(bike.getAttr());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        btndx = new javax.swing.JButton();
        btndown = new javax.swing.JButton();
        btnsx = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        jsVelocita = new javax.swing.JSlider();
        jsDirezione = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        btnBici = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHome.setText("reset 0 0");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btndx.setText("dx");
        btndx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndxActionPerformed(evt);
            }
        });

        btndown.setText("giu");
        btndown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndownActionPerformed(evt);
            }
        });

        btnsx.setText("sx");
        btnsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsxActionPerformed(evt);
            }
        });

        btnup.setText("su");
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });

        jsVelocita.setValue(0);
        jsVelocita.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsVelocitaStateChanged(evt);
            }
        });
        jsVelocita.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jsVelocitaPropertyChange(evt);
            }
        });

        jsDirezione.setMaximum(360);
        jsDirezione.setPaintLabels(true);
        jsDirezione.setValue(90);
        jsDirezione.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsDirezioneStateChanged(evt);
            }
        });
        jsDirezione.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jsDirezionePropertyChange(evt);
            }
        });

        jPanel1.setLayout(null);

        btnBici.setText("BICI");
        btnBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiciActionPerformed(evt);
            }
        });
        jPanel1.add(btnBici);
        btnBici.setBounds(30, 41, 54, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnsx, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndx))
                    .addComponent(jsVelocita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsDirezione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnup)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnsx)
                    .addComponent(btndx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btndown)
                        .addGap(11, 11, 11)
                        .addComponent(jsVelocita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsDirezione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        bike.move(0, 0);
        refreshBtn();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jsVelocitaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jsVelocitaPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jsVelocitaPropertyChange

    private void jsDirezionePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jsDirezionePropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jsDirezionePropertyChange

    private void jsVelocitaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsVelocitaStateChanged
        // TODO add your handling code here:
        bike.cambiaVelocita(jsVelocita.getValue());
        btnBici.setText(bike.getAttr());
    }//GEN-LAST:event_jsVelocitaStateChanged

    private void jsDirezioneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsDirezioneStateChanged
        // TODO add your handling code here:
        bike.cambiaDirezione(jsDirezione.getValue());
        btnBici.setText(bike.getAttr());
    }//GEN-LAST:event_jsDirezioneStateChanged

    private void btndxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndxActionPerformed
        // TODO add your handling code here:
        int newx;
        newx = bike.getX() + bike.getVelocita();
        if (newx > 500) {
            newx = 500;
        }
        bike.move(newx, bike.getY());
        refreshBtn();

    }//GEN-LAST:event_btndxActionPerformed

    private void btnsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsxActionPerformed
        // TODO add your handling code here:
        int newx;
        newx = bike.getX() - bike.getVelocita();
        if (newx < 0) {
            newx = 0;
        }
        bike.move(newx, bike.getY());
        refreshBtn();
    }//GEN-LAST:event_btnsxActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        // TODO add your handling code here:
        int newy;
        newy = bike.getY() - bike.getVelocita();
        if (newy < 0) {
            newy = 0;
        }
        bike.move(bike.getX(), newy);
        refreshBtn();
    }//GEN-LAST:event_btnupActionPerformed

    private void btndownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndownActionPerformed
        // TODO add your handling code here:
                int newy;
        newy = bike.getY() + bike.getVelocita();
        if (newy >400) {
            newy = 400;
        }
        bike.move(bike.getX(), newy);
        refreshBtn();

    }//GEN-LAST:event_btndownActionPerformed

    private void btnBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBiciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mondobici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mondobici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mondobici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mondobici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mondobici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBici;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btndown;
    private javax.swing.JButton btndx;
    private javax.swing.JButton btnsx;
    private javax.swing.JButton btnup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jsDirezione;
    private javax.swing.JSlider jsVelocita;
    // End of variables declaration//GEN-END:variables

    private void refreshBtn() {
    btnBici.setBounds(bike.getX(), bike.getY(),130,30);
    btnBici.setText(bike.getAttr());
    }
}
