/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIsample;

/**
 *
 * @author Paolo
 */
public class JFrameNewConsulente extends javax.swing.JFrame {

    /**
     * Creates new form JFrameScheda
     */
    public JFrameNewConsulente() {
        initComponents();
        this.setLocationRelativeTo(null); // fa comparire le schede sempre al centro
        btnAdd.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txInputNome = new javax.swing.JTextField();
        lblCognome = new javax.swing.JLabel();
        txInputCognome = new javax.swing.JTextField();
        txInputCosto = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblNewConsulente = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Costo");

        lblNome.setBackground(new java.awt.Color(30, 80, 30));
        lblNome.setForeground(new java.awt.Color(200, 200, 200));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Inserire nome");
        lblNome.setAutoscrolls(true);

        txInputNome.setBackground(new java.awt.Color(0, 0, 0));
        txInputNome.setFont(new java.awt.Font("URW Palladio L", 2, 20)); // NOI18N
        txInputNome.setForeground(new java.awt.Color(200, 200, 200));
        txInputNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txInputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txInputNomeActionPerformed(evt);
            }
        });

        lblCognome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCognome.setText("Inserire cognome");

        txInputCognome.setBackground(new java.awt.Color(0, 0, 0));
        txInputCognome.setFont(new java.awt.Font("Dialog", 2, 20)); // NOI18N
        txInputCognome.setForeground(new java.awt.Color(200, 200, 200));
        txInputCognome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txInputCognome.setToolTipText("");
        txInputCognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txInputCognomeActionPerformed(evt);
            }
        });

        txInputCosto.setBackground(new java.awt.Color(0, 0, 0));
        txInputCosto.setFont(new java.awt.Font("Dialog", 2, 20)); // NOI18N
        txInputCosto.setForeground(new java.awt.Color(200, 200, 200));
        txInputCosto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txInputCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txInputCostoActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(30, 30, 30));
        btnAdd.setForeground(new java.awt.Color(200, 200, 200));
        btnAdd.setText("AGGIUNGI");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("RITORNA");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNewConsulente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txInputCognome)
                    .addComponent(txInputNome)
                    .addComponent(txInputCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txInputCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCognome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txInputCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(lblNewConsulente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txInputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txInputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txInputNomeActionPerformed

    private void txInputCognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txInputCognomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txInputCognomeActionPerformed

    private void txInputCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txInputCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txInputCostoActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        float costo = Float.parseFloat(txInputCosto.getText());
        Consulente cNew = new Consulente(txInputNome.getText(), txInputCognome.getText(),costo);
        WinGestConsulenti.elConsulenti.add(cNew);
        lblNewConsulente.setText(cNew.infoHtml());
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblNewConsulente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txInputCognome;
    private javax.swing.JTextField txInputCosto;
    private javax.swing.JTextField txInputNome;
    // End of variables declaration//GEN-END:variables
}
