/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIsample;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author tss
 */
public class WinGestConsulenti extends javax.swing.JFrame {

    static Consulente consulenteCorrente;
    static ArrayList<Consulente> elConsulenti = new ArrayList<Consulente>();

    public String getElencoConsulenti() {
        String tx = "";
        for (int i = 0; i < elConsulenti.size(); i++) {
            tx += (i + 1) + ") " + elConsulenti.get(i).getNome() + " " + elConsulenti.get(i).getCognome() + " " + elConsulenti.get(i).getCosto() + "\n";
        }
        return tx;
    }

    /**
     * Creates new form winForm
     */
    public WinGestConsulenti() {
        initComponents(); // posiziona gli oggetti crafici
        this.setLocationRelativeTo(null); // fa comparire le schede sempre al centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblNome = new javax.swing.JLabel();
        btnScrivi = new javax.swing.JButton();
        txInputNome = new javax.swing.JTextField();
        lblCognome = new javax.swing.JLabel();
        txInputCognome = new javax.swing.JTextField();
        txOutput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpOutput = new javax.swing.JTextPane();
        txInputCosto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txDelete = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpOutputElConsulenti = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lsConsulenti = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnDeleteListElement = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnAddConsulenteFromNewTab = new javax.swing.JButton();

        jScrollPane3.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        lblNome.setBackground(new java.awt.Color(30, 80, 30));
        lblNome.setForeground(new java.awt.Color(200, 200, 200));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Inserire nome");
        lblNome.setAutoscrolls(true);

        btnScrivi.setBackground(new java.awt.Color(30, 30, 30));
        btnScrivi.setForeground(new java.awt.Color(200, 200, 200));
        btnScrivi.setText("SCRIVI");
        btnScrivi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnScriviMouseClicked(evt);
            }
        });
        btnScrivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScriviActionPerformed(evt);
            }
        });

        txInputNome.setBackground(new java.awt.Color(0, 0, 0));
        txInputNome.setFont(new java.awt.Font("URW Palladio L", 2, 20)); // NOI18N
        txInputNome.setForeground(new java.awt.Color(200, 200, 200));
        txInputNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txInputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txInputNomeActionPerformed(evt);
            }
        });

        lblCognome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCognome.setText("Inserire cognome");

        txInputCognome.setBackground(new java.awt.Color(0, 0, 0));
        txInputCognome.setFont(new java.awt.Font("Dialog", 2, 20)); // NOI18N
        txInputCognome.setForeground(new java.awt.Color(200, 200, 200));
        txInputCognome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txInputCognome.setToolTipText("");
        txInputCognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txInputCognomeActionPerformed(evt);
            }
        });

        txOutput.setBackground(new java.awt.Color(0, 0, 0));
        txOutput.setForeground(new java.awt.Color(0, 255, 0));
        txOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tpOutput.setBackground(new java.awt.Color(0, 0, 0));
        tpOutput.setForeground(new java.awt.Color(0, 255, 0));
        jScrollPane1.setViewportView(tpOutput);

        txInputCosto.setBackground(new java.awt.Color(0, 0, 0));
        txInputCosto.setFont(new java.awt.Font("Dialog", 2, 20)); // NOI18N
        txInputCosto.setForeground(new java.awt.Color(200, 200, 200));
        txInputCosto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txInputCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txInputCostoActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Costo");

        jLabel2.setText("Consulente Attuale");

        jLabel3.setText("log");

        jLabel4.setText("Elenco Consulenti");

        txDelete.setBackground(new java.awt.Color(0, 0, 0));
        txDelete.setForeground(new java.awt.Color(0, 255, 51));
        txDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDeleteActionPerformed(evt);
            }
        });

        btnDelete.setText("ELIMINA");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tpOutputElConsulenti.setBackground(new java.awt.Color(0, 0, 0));
        tpOutputElConsulenti.setForeground(new java.awt.Color(0, 255, 0));
        jScrollPane2.setViewportView(tpOutputElConsulenti);

        jLabel5.setText("N° consulente da eliminare");

        lsConsulenti.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(lsConsulenti);

        jLabel6.setText("Consulente da eliminare");

        btnDeleteListElement.setText("ELIMINA");
        btnDeleteListElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteListElementActionPerformed(evt);
            }
        });

        jLabel7.setText("Lable html");

        btnAddConsulenteFromNewTab.setText("ADD FROM NEW TAB");
        btnAddConsulenteFromNewTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddConsulenteFromNewTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txInputCognome, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(txInputNome)
                                    .addComponent(txInputCosto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnScrivi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 35, Short.MAX_VALUE)))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddConsulenteFromNewTab)
                            .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteListElement, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txInputCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCognome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txInputCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScrivi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnDelete))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnDeleteListElement))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(btnAddConsulenteFromNewTab)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txInputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txInputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txInputNomeActionPerformed

    private void btnScriviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScriviActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnScriviActionPerformed

    private void txInputCognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txInputCognomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txInputCognomeActionPerformed

    private void btnScriviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScriviMouseClicked
        // TODO add your handling code here:
        String tx = txInputNome.getText() + " " + txInputCognome.getText();
        txOutput.setText(tx);
        String t = tpOutput.getText() + tx + "\n";
        tpOutput.setText(t);
        float costo = Float.parseFloat(txInputCosto.getText());
        consulenteCorrente = new Consulente(txInputNome.getText(), txInputCognome.getText(), costo);
        elConsulenti.add(consulenteCorrente);
        tpOutputElConsulenti.setText(getElencoConsulenti()); //aggiorna tp
        lblInfo.setText(consulenteCorrente.infoHtml());
        refreshList(); //aggiorna lista
    }//GEN-LAST:event_btnScriviMouseClicked

    private void txInputCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txInputCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txInputCostoActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int n = Integer.parseInt(txDelete.getText());
            elConsulenti.remove(n - 1);
            tpOutputElConsulenti.setText(getElencoConsulenti()); //aggiorna tp
            refreshList(); //aggiorna lista
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDeleteActionPerformed

    private void btnDeleteListElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteListElementActionPerformed
        // TODO add your handling code here:
        int index = lsConsulenti.getSelectedIndex();
        elConsulenti.remove(index);
        tpOutputElConsulenti.setText(getElencoConsulenti()); //aggiorna tp
        refreshList(); //aggiorna lista
    }//GEN-LAST:event_btnDeleteListElementActionPerformed

    private void btnAddConsulenteFromNewTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConsulenteFromNewTabActionPerformed
        // TODO add your handling code here:
        JFrameNewConsulente jf = new JFrameNewConsulente();
        jf.setVisible(true); // apre la nuova scheda
        // oppure new JFrameNewConsulente().setVisible(true);
    }//GEN-LAST:event_btnAddConsulenteFromNewTabActionPerformed

    /**
     * Metodo che refresha tutti i campi visibili quando la finestra principale
 riprende il focus, ad esempio tornando dala finestra JFrameNewConsulente
     * @param evt 
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        tpOutputElConsulenti.setText(getElencoConsulenti()); //aggiorna tp
        refreshList();
    }//GEN-LAST:event_formWindowGainedFocus

    public void refreshList() {
        DefaultListModel listModel = new DefaultListModel();
        int i = 1;
        for (Consulente c : elConsulenti) {
            String item = i + ") " + c.getNome() + " " + c.getCognome();
            listModel.addElement(item);
            i++;
        }
        lsConsulenti.setModel(listModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinGestConsulenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinGestConsulenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinGestConsulenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinGestConsulenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinGestConsulenti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddConsulenteFromNewTab;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteListElement;
    private javax.swing.JButton btnScrivi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JList<String> lsConsulenti;
    private javax.swing.JTextPane tpOutput;
    private javax.swing.JTextPane tpOutputElConsulenti;
    private javax.swing.JTextField txDelete;
    private javax.swing.JTextField txInputCognome;
    private javax.swing.JTextField txInputCosto;
    private javax.swing.JTextField txInputNome;
    private javax.swing.JTextField txOutput;
    // End of variables declaration//GEN-END:variables
}
