/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tss.ciac.abstractandinterfaceveicolo;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JButton;

/**
 *
 * @author Paolo
 */
public class GestVeicoli extends javax.swing.JFrame {

    Bicicletta bike;

    /**
     * Creates new form GestVeicoli
     */
    public GestVeicoli() {
        initComponents();
        bike = new Bicicletta(0, 0, 0, 90); //creo oggetto bike
        jButtonBici.setLocation(0, 0);
        jButtonBici.setBounds(bike.getX(), bike.getY(), 160, 30);
        jButtonBici.setText(bike.getAttr());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReset = new javax.swing.JButton();
        jButtonBici = new javax.swing.JButton();
        jButtonDx = new javax.swing.JButton();
        jButtonUp = new javax.swing.JButton();
        jButtonSx = new javax.swing.JButton();
        jButtonDown = new javax.swing.JButton();
        jSliderSpeed = new javax.swing.JSlider();
        jSliderDirection = new javax.swing.JSlider();
        jButtonMove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonReset.setText("RESET");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonDx.setText("DX");
        jButtonDx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDxActionPerformed(evt);
            }
        });

        jButtonUp.setText("UP");
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });

        jButtonSx.setText("SX");
        jButtonSx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSxActionPerformed(evt);
            }
        });

        jButtonDown.setText("DOWN");
        jButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownActionPerformed(evt);
            }
        });

        jSliderSpeed.setMaximumSize(new java.awt.Dimension(500, 16));
        jSliderSpeed.setMinimumSize(new java.awt.Dimension(0, 16));
        jSliderSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSpeedStateChanged(evt);
            }
        });

        jSliderDirection.setMaximum(359);
        jSliderDirection.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderDirectionStateChanged(evt);
            }
        });

        jButtonMove.setText("MOVE");
        jButtonMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBici, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonSx, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonDown, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonDx, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jSliderSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSliderDirection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonMove, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDx)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonSx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDown)
                .addGap(18, 18, 18)
                .addComponent(jSliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMove)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        bike.setX(0);
        bike.setY(0);
        jButtonBici.setText(bike.getAttr());

        jButtonBici.setBounds(0, 0, 160, 30);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jSliderSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSpeedStateChanged
        // TODO add your handling code here:
        bike.setSpeed(jSliderSpeed.getValue());
        jButtonBici.setText(bike.getAttr());
        
        jButtonBici.setBounds(bike.getX(), bike.getY(), 160, 30);
    }//GEN-LAST:event_jSliderSpeedStateChanged

    private void jSliderDirectionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderDirectionStateChanged
        // TODO add your handling code here:
        bike.setDirection(jSliderDirection.getValue());
        jButtonBici.setText(bike.getAttr());
        
        jButtonBici.setBounds(bike.getX(), bike.getY(), 160, 30);
    }//GEN-LAST:event_jSliderDirectionStateChanged

    private void jButtonSxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSxActionPerformed
        // TODO add your handling code here:
        int newX;
        newX = bike.getX() - bike.getSpeed();
        if (newX < 0) {
            newX = 0;
        }
        bike.setX(newX);

        jButtonBici.setBounds(bike.getX(), bike.getY(), 160, 30);
    }//GEN-LAST:event_jButtonSxActionPerformed

    private void jButtonDxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDxActionPerformed
        // TODO add your handling code here:
        int newX;
        newX = bike.getX() + bike.getSpeed();
        if (newX > 500) {
            newX = 500;
        }
        bike.setX(newX);

        jButtonBici.setBounds(bike.getX(), bike.getY(), 160, 30);
    }//GEN-LAST:event_jButtonDxActionPerformed

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
        // TODO add your handling code here:
        int newY;
        newY = bike.getY() - bike.getSpeed();
        if (newY < 0) {
            newY = 0;
        }
        bike.setY(newY);

        jButtonBici.setBounds(bike.getX(), bike.getY(), 160, 30);
    }//GEN-LAST:event_jButtonUpActionPerformed

    private void jButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed
        // TODO add your handling code here:
        int newY;
        newY = bike.getY() + bike.getSpeed();
        if (newY > 500) {
            newY = 500;
        }
        bike.setY(newY);

        jButtonBici.setBounds(bike.getX(), bike.getY(), 160, 30);
    }//GEN-LAST:event_jButtonDownActionPerformed

    private void jButtonMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveActionPerformed
        // TODO add your handling code here:
        double newX = (Math.cos(Math.toRadians(bike.getDirection())))*bike.getSpeed();
        int x=(int)newX+bike.getX();
        if (x > 500) {
            x = 500;
        }
        if (x < 0) {
            x = 0;
        }
        bike.setX(x);
        double newY = Math.sin(Math.toRadians(bike.getDirection()))*bike.getSpeed();
        int y=(int)newY+bike.getY();
        if (y > 500) {
            y = 500;
        }
        if (y < 0) {
            y = 0;
        }
        bike.setY(y);
        jButtonBici.setBounds(bike.getX(), bike.getY(), 160, 30);
    }//GEN-LAST:event_jButtonMoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestVeicoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestVeicoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestVeicoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestVeicoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestVeicoli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBici;
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonDx;
    private javax.swing.JButton jButtonMove;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSx;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JSlider jSliderDirection;
    private javax.swing.JSlider jSliderSpeed;
    // End of variables declaration//GEN-END:variables
}
